### PR TITLE
Agnostic class/method name string convertion

### PR DESCRIPTION
**Pull request by lweberk**
- Fix Issue #19
- Allow any printable character to be used in name strings

### CODE REVIEW

**Comment by lweberk** [comment]
Hmm the traceback uppon a assertion error ends up outputting a method name like it_serializes0c32xcorrectly. This commit would require some makeup on the error output perhaps.

**Comment by alfredodeza** [comment]
I don't think this approach is the correct one. The sorting should be done implicitly and konira should respect the order in which they were written. I will come up with a mechanism that can respect that fact. 

Thank you for the time and effort put into this, unfortunately, it was done at a time where I was unavailable to provide guidance. 

Feel free to add/contribute to the discussion on the ticket.

**Comment by lweberk** [comment]
Well that would be easily done by further prefixing something like it_l<lno>x, using the same encoding approach. This would sort them by line number and thus implicitly.

As for this patch, it actually allows you to use any char in your description names, which is another issue. It does not exclusively add support for explicit alphabetical ordering through ordinal numbering. Shure you don't want to review it before closing?

Either way, I am very sorry but we decided to fall back to bare pytest, since we went from problem to problem with Konira, since it drops too much of the test code metadata. That said we are bailing our efforts.

**Comment by alfredodeza** [comment]
I wasn't aware there were other problems with Konira. Using `py.test` would be at the top of my list as well.

Maybe I got confused for a pull request that referenced the alphabetical ordering issue but addressed the "any character" as a name (did you opened an issue on that?).

I will need to get some notes down on contributing, but generally I prefer a pull request addressing a single problem (even better if associated to a direct issue).

To recap:
- I don't think allowing any printable character for signatures is the way to go (Python does it similarly).
- Test method ordering should be implicit (a-la `py.test`) where nothing else is needed other than the order you write the tests (but this will take a bit of an effort on my end)

If the ordering is a must, I promise to have a solution within a week following my recap from above. If you like `py.test` features, please note that there is a `pytest-konira` plugin as well.

**Pull request closed without merging**
