### PR TITLE
Fixed file system example

### PR DESCRIPTION
**Pull request by evelynmitchell**
The example used, but didn't import os
Also, it assumed the file existed.
And, the open command didn't work.

### CODE REVIEW

**Comment by alfredodeza** [comment]
Thank you for the oull request!
 You did find an omission. Could you modify it so the import is at the top (just once) ?

That would look like less duplication.

Also, `os.open` is not necessary as `open` is a Python built-in.

**Comment by alfredodeza** [comment]
Mnnn you say `open` didn't work?Maybe the example  is assuming too much ? `/tmp` would need to exist.

For demonstration purposes I think this demonstrates the capabilities cirrectly though.

**Comment by evelynmitchell** [comment]
I've moved the import.

**Comment by alfredodeza** [comment]
Thank you very much!

**Pull request merged**
